### ISSUE TITLE
Bug dans la requête SQL

### ISSUE THREAD

**Issue by thierrypigot** [BeAPI/ACF-PHP-Recovery#14]
Salut, 
Si le groupe de champs a un apostrophe cela casse la requête SQL et en plus ce n'est pas très secure ;)

`$sql = "SELECT ID, post_title FROM $wpdb->posts WHERE post_title LIKE '%{$field_group['title']}%' AND post_type='".ACFPR_GROUP_POST_TYPE."'";`

Peut être utiliser un "prepare" ?

Thierry

**Comment by MaximeCulea** [comment]
Hello @thierrypigot,
Merci pour ton ticket.

Comme nous développons uniquement en anglais, nous n'avons pas encore eu de soucis de ce côté la. Mais tu as raison, un escape ne mange pas de pain, il faudrait en ajouter un.

Soit un escape fait l'affaire, car ce n'est pas un plugin à laissé activé, soit passer par un prepare.
Te sens-tu chaud pour faire un PR ?
Ou alors on s'en charge lors de notre prochaine R&D ?

Merci

**Comment by MaximeCulea** [comment]
Following https://github.com/BeAPI/ACF-PHP-Recovery/pull/15, closing this.
Thx
