### ISSUE TITLE
Conditional logic

### ISSUE THREAD

**Issue by eoutvik** [BeAPI/ACF-PHP-Recovery#4]
First of all: Great plugin :) 
Only issue we're having is that fields with conditional logic are ignored and not imported.

**Comment by MaximeCulea** [comment]
Hi @eoutvik,

As we just take ownership of this project for maintening it, can I ask you if it is always on topical ?

Thx

**Comment by eoutvik** [comment]
Hi. Can't remember what the outcome of this issue was. I think we just updated the ACF plugin to V5 when that was released and the new acf-json cache solved it for us.

**Comment by khromov** [comment]
Like @eoutvik wrote this isn't a problem any more since ACF 5.

**Comment by MaximeCulea** [comment]
With your help @eoutvik and @khromov, I close this issue !
Thx
