### ISSUE TITLE
Thanks! How can I donate?

### ISSUE THREAD

**Issue by jambox** [BeAPI/ACF-PHP-Recovery#8]
I wanted to donate to your project because you just saved me a ton of time! How can I do that?

Thanks!

**Comment by garrettboatman** [comment]
@seamusleahy should post his $cashtag.

https://cash.me/

**Comment by jakehills** [comment]
I'd also like to donate - unprecedented amount of time/money saved.

**Comment by MaximeCulea** [comment]
Hi @jambox, @garrettboatman, @jakehills,

As up to now Seamusleahy didn't answer and we have just taken the ownership of this project, we can consider that this is not anymore topical.

So I close this issue.
Thx
