### ISSUE TITLE
Unable to find options page

### ISSUE THREAD

**Issue by simplenotezy** [BeAPI/ACF-PHP-Recovery#9]
I am unable to find the options page. After installing & activating, no submenu is added to "Custom fields".

WP Version: 4.2
ACF version: 4.4.1

**Comment by ElvarisGjinali** [comment]
I have a same issue.

WP Version: 4.2.2
ACF version: 4.4.1

**Comment by seamusleahy** [comment]
Thanks for the report. I'll look into it.

**Comment by ElvarisGjinali** [comment]
Hi seamusleahy,

the problem comes from wrong branch download, I downloading from master branch which plugin is for the  acf v5, apologies :) btw great job i save a lot of time.

**Comment by MaximeCulea** [comment]
This is a misswriting in the url in admin's plugin page (wp-admin/edit.php?post_type=acf-field-group&page=acf-php-import)
The link to acf recovery page is : wp-admin/edit.php?post_type=acf&page=acf-php-import
which in fact must be : wp-admin/edit.php?post_type=acf-field-group&page=acf-php-import

**Comment by joe-tofu** [comment]
Seems like the plugin stopped working somewhere along the line. 

WP Version: 4.5.3
ACF Version: 4.4.8
ACF PHP Recovery Tool Version: 0.3

There's no link to the options-page under the ACF-controls. If I click on the link to the options-page under the plugin-section (or if I use the Link @MaximeCulea suggested) I get the following error:

> You do not have sufficient permissions to access this page.

**Comment by MaximeCulea** [comment]
@joe-tofu when installing ACF, you do not have a page wp-admin/edit.php?post_type=acf-field-group ?

**Comment by Greg-Boggs** [comment]
When I enable the plugin, the dashboard links to a broken page:

/wp-admin/edit.php?post_type=acf&page=acf-php-import

The sidebar links to the correct path:

wp-admin/edit.php?post_type=acf-field-group&page=acf-php-import

**Comment by MaximeCulea** [comment]
Hello @Greg-Boggs !
That's the answer I was waiting for ;)
Thx for the PR #13 BTW, that, I have just merged.
So I close this issue.
Thx.
